[phases.setup]
nixPkgs = ['nodejs_22', 'python3', 'gcc', 'pkg-config']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build --workspace=apps/web', 'npm run build --workspace=apps/server']

[start]
cmd = 'cd apps/server && npm run start'
