[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start --prefix apps/server"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
